# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollchoicebase',
            old_name='poll',
            new_name='poll_base',
        ),
    ]
